-- Observability/governance setup.

-- 1) Schema and object privileges (GOVERNANCE, INTELLIGENCE)
USE ROLE SECURITYADMIN;

-- Grant schema privileges
GRANT USAGE ON DATABASE MEDICARE_POS_DB TO ROLE MEDICARE_POS_INTELLIGENCE;
GRANT USAGE ON SCHEMA MEDICARE_POS_DB.GOVERNANCE TO ROLE MEDICARE_POS_INTELLIGENCE;

-- Grant object creation privileges
GRANT CREATE TABLE ON SCHEMA MEDICARE_POS_DB.GOVERNANCE TO ROLE MEDICARE_POS_INTELLIGENCE;
GRANT CREATE VIEW ON SCHEMA MEDICARE_POS_DB.GOVERNANCE TO ROLE MEDICARE_POS_INTELLIGENCE;
GRANT CREATE PROCEDURE ON SCHEMA MEDICARE_POS_DB.GOVERNANCE TO ROLE MEDICARE_POS_INTELLIGENCE;
GRANT CREATE TASK ON SCHEMA MEDICARE_POS_DB.GOVERNANCE TO ROLE MEDICARE_POS_INTELLIGENCE;


-- 2) Schema and object privileges (INTELLIGENCE)
-- Needed by sql/observability/04_create_quality_tables.sql
GRANT USAGE ON SCHEMA MEDICARE_POS_DB.INTELLIGENCE TO ROLE MEDICARE_POS_INTELLIGENCE;
GRANT CREATE EVENT TABLE ON SCHEMA MEDICARE_POS_DB.INTELLIGENCE TO ROLE MEDICARE_POS_INTELLIGENCE;
GRANT CREATE TASK ON SCHEMA MEDICARE_POS_DB.INTELLIGENCE TO ROLE MEDICARE_POS_INTELLIGENCE;

-- 3) Accountadmin for Task execution grants
USE ROLE ACCOUNTADMIN;

-- Required to resume/execute tasks.
GRANT EXECUTE TASK ON ACCOUNT TO ROLE MEDICARE_POS_INTELLIGENCE;

-- Cortex database role for AI features.
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE MEDICARE_POS_INTELLIGENCE;

-- Grant AI Observability application role
-- This is required to access SNOWFLAKE.LOCAL.AI_OBSERVABILITY_EVENTS
GRANT APPLICATION ROLE SNOWFLAKE.AI_OBSERVABILITY_EVENTS_LOOKUP
TO ROLE MEDICARE_POS_INTELLIGENCE;

-- Verify grants
SHOW GRANTS TO ROLE MEDICARE_POS_INTELLIGENCE;

-- Test access

-- Switch to working role
USE ROLE MEDICARE_POS_INTELLIGENCE;

-- Test AI Observability access
SELECT COUNT(*) AS ai_event_count
FROM SNOWFLAKE.LOCAL.AI_OBSERVABILITY_EVENTS
LIMIT 1;
