-- Teardown all deployed Snowflake objects for this repo.
-- WARNING: destructive. Run only when you want a full reset.

USE ROLE ACCOUNTADMIN;

-- Drop agent first (depends on analytics objects/stage).
DROP AGENT IF EXISTS MEDICARE_POS_DB.ANALYTICS.DMEPOS_INTELLIGENCE_AGENT_SQL;

-- Drop search services.
DROP CORTEX SEARCH SERVICE IF EXISTS MEDICARE_POS_DB.SEARCH.HCPCS_SEARCH_SVC;
DROP CORTEX SEARCH SERVICE IF EXISTS MEDICARE_POS_DB.SEARCH.DEVICE_SEARCH_SVC;
DROP CORTEX SEARCH SERVICE IF EXISTS MEDICARE_POS_DB.SEARCH.PROVIDER_SEARCH_SVC;
DROP CORTEX SEARCH SERVICE IF EXISTS MEDICARE_POS_DB.SEARCH.PDF_SEARCH_SVC;

-- Drop schemas explicitly (database drop below also cascades).
DROP SCHEMA IF EXISTS MEDICARE_POS_DB.RAW CASCADE;
DROP SCHEMA IF EXISTS MEDICARE_POS_DB.CURATED CASCADE;
DROP SCHEMA IF EXISTS MEDICARE_POS_DB.ANALYTICS CASCADE;
DROP SCHEMA IF EXISTS MEDICARE_POS_DB.SEARCH CASCADE;
DROP SCHEMA IF EXISTS MEDICARE_POS_DB.INTELLIGENCE CASCADE;
DROP SCHEMA IF EXISTS MEDICARE_POS_DB.GOVERNANCE CASCADE;
DROP SCHEMA IF EXISTS MEDICARE_POS_DB.OBSERVABILITY CASCADE;

-- Drop compute and roles.
DROP WAREHOUSE IF EXISTS MEDICARE_POS_WH;
DROP ROLE IF EXISTS MEDICARE_POS_ADMIN;
DROP ROLE IF EXISTS MEDICARE_POS_INTELLIGENCE;

-- Final database cleanup.
DROP DATABASE IF EXISTS MEDICARE_POS_DB;

SELECT 'teardown_complete' AS status;
SELECT 'redeploy_with_make_demo_or_make_deploy_all' AS next_step;
